AdventureWorks.Directory/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace AdventureWorks.Directory.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

AdventureWorks.Directory/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/Mobile/css", "~/Content/jquerymobile/css")    
    @Scripts.Render("~/bundles/jquery", "~/bundles/jquerymobile")

</head>
<body>
    <div data-role="page" data-theme="c">
      @*  @Html.Partial("_ViewSwitcher")*@
        @*<div data-role="header" align="center"  data-theme="c">
            <span><button onclick="location.href='@Url.Action("Index", "Home")';return false;">Home</button></span>
        </div>*@
        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()
            <script>
                $(document).ready(function () {
                    $.mobile.ajaxEnabled = false;
                });
            </script>
            @RenderSection("scripts", required: false)
        </div>
    </div>
</body>
</html>

AdventureWorks.Directory/Views/Shared/_Layout.cshtml
 @using DevExpress.Web.Mvc.UI;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
      @Scripts.Render("~/bundles/jquery")
    @Html.DevExpress().GetScripts( 
        new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout }, 
        new Script { ExtensionSuite = ExtensionSuite.GridView }, 
        new Script { ExtensionSuite = ExtensionSuite.Editors }
    ) 
   
</head>
<body>
   @* @Html.Partial("_ViewSwitcher")*@
    @Html.DevExpress().GetStyleSheets( 
        new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout }, 
        new StyleSheet { ExtensionSuite = ExtensionSuite.Editors }, 
        new StyleSheet { ExtensionSuite = ExtensionSuite.GridView }   
    )

   

   <div id="navigation">
        <div id="main-nav">
            @*<span>@Html.Label("Search Employees", new { @class = "header_Label" })</span>*@
            <ul class="tabbed">      
                <li>
                    @Html.MenuItem("Employees", "SearchEmployees", "Home")
                    </li>
            </ul>
            <div class="clearer">&nbsp;</div>
        </div>
    </div>
    
    @RenderSection("scripts", required: false)
    @RenderBody()
    
</body>
</html>

AdventureWorks.Directory/Views/Shared/_ViewSwitcher.cshtml
@*@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
} 
else
{
     @:Not Mobile/Get
}*@